version: '3'

services:
  #mysql for db storage
  mysql8:
    image: mysql:8
    restart: always
    container_name: hannahs_haus_db
    environment:
      MYSQL_ROOT_PASSWORD: NarrativeNonsense21!
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_user
      MYSQL_PASSWORD: secret
    volumes:
      - ./:/application
    ports:
      - '9405:3306'
    networks:
      - application
  #cakephp for framework
  php-fpm:
    image: webdevops/php-nginx:8.2
    container_name: myapp-webserver
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
      - DATABASE_URL=mysql://my_user:secret@hannahs_haus_db/my_app
    ports:
      - "80:80"
    networks:
      - application
networks:
  application: 